"""
解码 Agent 列出的工具
"""
import json

response_text = """
data: {"type": "session", "session_id": "3d33ed51-2a61-4e91-9c22-048d67d2bf63"}

data: {"type": "content", "content": "\u597d\u7684"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u95ee"}
data: {"type": "content", "content": "\u7684\u662f"}
data: {"type": "content", "content": "\u201c"}
data: {"type": "content", "content": "\u4f60"}
data: {"type": "content", "content": "\u6709\u4ec0\u4e48"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u53ef\u4ee5"}
data: {"type": "content", "content": "\u4f7f\u7528"}
data: {"type": "content", "content": "\uff1f"}
data: {"type": "content", "content": "\u8bf7"}
data: {"type": "content", "content": "\u5217\u51fa"}
data: {"type": "content", "content": "\u6240\u6709"}
data: {"type": "content", "content": "\u53ef\u7528"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u3002\u201d"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u6211"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u5148"}
data: {"type": "content", "content": "\u67e5\u770b"}
data: {"type": "content", "content": "\u63d0\u4f9b\u7684"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u5217\u8868"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u7136\u540e"}
data: {"type": "content", "content": "\u6574\u7406"}
data: {"type": "content", "content": "\u51fa"}
data: {"type": "content", "content": "\u6240\u6709"}
data: {"type": "content", "content": "\u53ef\u7528"}
data: {"type": "content", "content": "\u7684"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\uff0c\u5e76"}
data: {"type": "content", "content": "\u7528"}
data: {"type": "content", "content": "\u4e2d\u6587"}
data: {"type": "content", "content": "\u5217\u51fa"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n\n\u9996\u5148"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u6211"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u786e\u8ba4"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u7684\u95ee\u9898"}
data: {"type": "content", "content": "\u662f\u8981"}
data: {"type": "content", "content": "\u6211"}
data: {"type": "content", "content": "\u5217\u51fa"}
data: {"type": "content", "content": "\u6240\u6709"}
data: {"type": "content", "content": "\u53ef\u7528"}
data: {"type": "content", "content": "\u7684"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\u6839\u636e"}
data: {"type": "content", "content": "\u63d0\u4f9b\u7684"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u5217\u8868"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u91cc\u9762"}
data: {"type": "content", "content": "\u6709\u5f88\u591a"}
data: {"type": "content", "content": "\u4e0d\u540c\u7684"}
data: {"type": "content", "content": "\u51fd\u6570"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u6bcf\u4e2a"}
data: {"type": "content", "content": "\u90fd\u6709"}
data: {"type": "content", "content": "\u540d\u79f0"}
data: {"type": "content", "content": "\u3001"}
data: {"type": "content", "content": "\u63cf\u8ff0"}
data: {"type": "content", "content": "\u548c"}
data: {"type": "content", "content": "\u53c2\u6570"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u53ef\u80fd"}
data: {"type": "content", "content": "\u5e0c\u671b"}
data: {"type": "content", "content": "\u5f97\u5230"}
data: {"type": "content", "content": "\u4e00\u4e2a"}
data: {"type": "content", "content": "\u6e05\u6670"}
data: {"type": "content", "content": "\u7684"}
data: {"type": "content", "content": "\u5217\u8868"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u8bf4\u660e"}
data: {"type": "content", "content": "\u6709\u54ea\u4e9b"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u4ee5\u53ca"}
data: {"type": "content", "content": "\u5b83\u4eec"}
data: {"type": "content", "content": "\u7684\u529f\u80fd"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n\n\u6211"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u68c0\u67e5"}
data: {"type": "content", "content": "\u63d0\u4f9b\u7684"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u90e8\u5206"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u91cc\u9762"}
data: {"type": "content", "content": "\u5217"}
data: {"type": "content", "content": "\u51fa"}
data: {"type": "content", "content": "\u4e86"}
data: {"type": "content", "content": "\u591a\u4e2a"}
data: {"type": "content", "content": "\u51fd\u6570"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u6bd4\u5982"}
data: {"type": "content", "content": "write"}
data: {"type": "content", "content": "_long"}
data: {"type": "content", "content": "_term"}
data: {"type": "content", "content": "_memory"}
data: {"type": "content", "content": "\u3001"}
data: {"type": "content", "content": "search"}
data: {"type": "content", "content": "_all"}
data: {"type": "content", "content": "_mem"}
data: {"type": "content", "content": "ories"}
data: {"type": "content", "content": "\u7b49"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\u6bcf\u4e2a"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u90fd\u6709"}
data: {"type": "content", "content": "\u8be6\u7ec6"}
data: {"type": "content", "content": "\u63cf\u8ff0"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u6211"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u628a\u8fd9\u4e9b"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u5206\u7c7b"}
data: {"type": "content", "content": "\u6216\u8005"}
data: {"type": "content", "content": "\u9010\u4e00"}
data: {"type": "content", "content": "\u5217\u51fa"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u7528"}
data: {"type": "content", "content": "\u4e2d\u6587"}
data: {"type": "content", "content": "\u89e3\u91ca"}
data: {"type": "content", "content": "\u6bcf\u4e2a"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u7684\u4f5c\u7528"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n\n\u4e0d\u8fc7"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u53ef\u80fd"}
data: {"type": "content", "content": "\u53ea\u9700\u8981"}
data: {"type": "content", "content": "\u77e5\u9053"}
data: {"type": "content", "content": "\u6709\u54ea\u4e9b"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u4e0d\u9700\u8981"}
data: {"type": "content", "content": "\u6df1\u5165"}
data: {"type": "content", "content": "\u53c2\u6570"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\u4f46"}
data: {"type": "content", "content": "\u6839\u636e"}
data: {"type": "content", "content": "\u4e4b\u524d\u7684"}
data: {"type": "content", "content": "\u6307\u793a"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u5f53"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u5904\u7406"}
data: {"type": "content", "content": "\u7279\u5b9a"}
data: {"type": "content", "content": "\u4efb\u52a1"}
data: {"type": "content", "content": "\u65f6"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u5e94\u8be5"}
data: {"type": "content", "content": "\u4e3b\u52a8"}
data: {"type": "content", "content": "\u4f7f\u7528"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\u4f46"}
data: {"type": "content", "content": "\u8fd9\u6b21"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u53ea\u662f"}
data: {"type": "content", "content": "\u8be2\u95ee"}
data: {"type": "content", "content": "\u6709\u54ea\u4e9b"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u6240\u4ee5"}
data: {"type": "content", "content": "\u53ef\u80fd"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u76f4\u63a5"}
data: {"type": "content", "content": "\u5217\u51fa"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n\n\u4f46"}
data: {"type": "content", "content": "\u6839\u636e"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u63d0\u4f9b\u7684"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u5217\u8868"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u91cc\u9762"}
data: {"type": "content", "content": "\u6709\u5f88\u591a"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u6211"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u9010\u4e00"}
data: {"type": "content", "content": "\u63d0\u53d6"}
data: {"type": "content", "content": "\u540d\u79f0"}
data: {"type": "content", "content": "\u548c"}
data: {"type": "content", "content": "\u63cf\u8ff0"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u7528"}
data: {"type": "content", "content": "\u4e2d\u6587"}
data: {"type": "content", "content": "\u7b80"}
data: {"type": "content", "content": "\u8981"}
data: {"type": "content", "content": "\u8bf4\u660e"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\u4f8b\u5982"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "calculator"}
data: {"type": "content", "content": "\u662f"}
data: {"type": "content", "content": "\u6570\u5b66"}
data: {"type": "content", "content": "\u8ba1\u7b97"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "datetime"}
data: {"type": "content", "content": "\u662f"}
data: {"type": "content", "content": "\u83b7\u53d6"}
data: {"type": "content", "content": "\u65f6\u95f4"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "random"}
data: {"type": "content", "content": "\u751f\u6210"}
data: {"type": "content", "content": "\u968f\u673a"}
data: {"type": "content", "content": "\u6570"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "json"}
data: {"type": "content", "content": "_format"}
data: {"type": "content", "content": "\u683c\u5f0f"}
data: {"type": "content", "content": "\u5316"}
data: {"type": "content", "content": "JSON"}
data: {"type": "content", "content": "\u7b49"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n\n\u53e6\u5916"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u6ce8\u610f"}
data: {"type": "content", "content": "\u6709\u4e9b"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u662f"}
data: {"type": "content", "content": "\u5173\u4e8e"}
data: {"type": "content", "content": "\u8bb0\u5fc6"}
data: {"type": "content", "content": "\u7ba1\u7406"}
data: {"type": "content", "content": "\u7684"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u6bd4\u5982"}
data: {"type": "content", "content": "write"}
data: {"type": "content", "content": "_long"}
data: {"type": "content", "content": "_term"}
data: {"type": "content", "content": "_memory"}
data: {"type": "content", "content": "\u3001"}
data: {"type": "content", "content": "search"}
data: {"type": "content", "content": "_mem"}
data: {"type": "content", "content": "ories"}
data: {"type": "content", "content": "\u7b49"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u8fd9\u4e9b"}
data: {"type": "content", "content": "\u53ef\u80fd"}
data: {"type": "content", "content": "\u5c5e\u4e8e"}
data: {"type": "content", "content": "\u8bb0\u5fc6"}
data: {"type": "content", "content": "\u7ba1\u7406"}
data: {"type": "content", "content": "\u6a21\u5757"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u5c06"}
data: {"type": "content", "content": "\u6240\u6709"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u5206"}
data: {"type": "content", "content": "\u95e8"}
data: {"type": "content", "content": "\u522b"}
data: {"type": "content", "content": "\u7c7b"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u4f46"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u53ef\u80fd"}
data: {"type": "content", "content": "\u5e0c\u671b"}
data: {"type": "content", "content": "\u5168\u90e8"}
data: {"type": "content", "content": "\u5217\u51fa"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n\n\u73b0\u5728"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u5c06"}
data: {"type": "content", "content": "\u6240\u6709"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u540d\u79f0"}
data: {"type": "content", "content": "\u548c"}
data: {"type": "content", "content": "\u63cf\u8ff0"}
data: {"type": "content", "content": "\u7528"}
data: {"type": "content", "content": "\u4e2d\u6587"}
data: {"type": "content", "content": "\u7b80"}
data: {"type": "content", "content": "\u8981"}
data: {"type": "content", "content": "\u8bf4\u660e"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u53ef\u80fd"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u68c0\u67e5"}
data: {"type": "content", "content": "\u6bcf\u4e2a"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u7684"}
data: {"type": "content", "content": "\u63cf\u8ff0"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u8f6c\u6362"}
data: {"type": "content", "content": "\u6210"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u5bb9\u6613"}
data: {"type": "content", "content": "\u7406\u89e3"}
data: {"type": "content", "content": "\u7684\u8bed\u8a00"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n\n\u4f8b\u5982"}
data: {"type": "content", "content": "\uff1a"}
data: {"type": "content", "content": "\n-"}
data: {"type": "content", "content": " calculator"}
data: {"type": "content", "content": "\uff1a"}
data: {"type": "content", "content": "\u6570\u5b66"}
data: {"type": "content", "content": "\u8ba1\u7b97"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u652f\u6301"}
data: {"type": "content", "content": "\u57fa\u672c"}
data: {"type": "content", "content": "\u8fd0\u7b97"}
data: {"type": "content", "content": "\u3001"}
data: {"type": "content", "content": "\u4e09\u89d2"}
data: {"type": "content", "content": "\u51fd\u6570"}
data: {"type": "content", "content": "\u7b49"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n-"}
data: {"type": "content", "content": " datetime"}
data: {"type": "content", "content": "\uff1a"}
data: {"type": "content", "content": "\u83b7\u53d6"}
data: {"type": "content", "content": "\u5f53\u524d"}
data: {"type": "content", "content": "\u65e5\u671f"}
data: {"type": "content", "content": "\u548c"}
data: {"type": "content", "content": "\u65f6\u95f4"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n-"}
data: {"type": "content", "content": " random"}
data: {"type": "content", "content": "\uff1a"}
data: {"type": "content", "content": "\u751f\u6210"}
data: {"type": "content", "content": "\u968f\u673a"}
data: {"type": "content", "content": "\u6570"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n-"}
data: {"type": "content", "content": " json"}
data: {"type": "content", "content": "_format"}
data: {"type": "content", "content": "\uff1a"}
data: {"type": "content", "content": "\u683c\u5f0f"}
data: {"type": "content", "content": "\u5316"}
data: {"type": "content", "content": "JSON"}
data: {"type": "content", "content": "\u5b57\u7b26\u4e32"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n\n\u5176\u4ed6"}
data: {"type": "content", "content": "\u5de5\u5177"}
data: {"type": "content", "content": "\u5982"}
data: {"type": "content", "content": "write"}
data: {"type": "content", "content": "_long"}
data: {"type": "content", "content": "_term"}
data: {"type": "content", "content": "_memory"}
data: {"type": "content", "content": "\u3001"}
data: {"type": "content", "content": "search"}
data: {"type": "content", "content": "_all"}
data: {"type": "content", "content": "_mem"}
data: {"type": "content", "content": "ories"}
data: {"type": "content", "content": "\u7b49"}
data: {"type": "content", "content": "\uff0c"}
data: {"type": "content", "content": "\u9700\u8981"}
data: {"type": "content", "content": "\u540c\u6837"}
data: {"type": "content", "content": "\u5904\u7406"}
data: {"type": "content", "content": "\u3002"}
data: {"type": "content", "content": "\n\n\u4f46"}
data: {"type": "content", "content": "\u7528\u6237"}
data: {"type": "content", "content": "\u53ef\u80fd"}
data: {"type": "content", "content": "\u5e0c\u671b"}
"""

# 提取并解码内容
full_text = ""
for line in response_text.strip().split('\n'):
    if line.startswith('data: '):
        try:
            data = json.loads(line[6:])
            if data.get('type') == 'content':
                full_text += data.get('content', '')
        except:
            pass

print("=" * 80)
print("🤖 Agent 列出的可用工具")
print("=" * 80)
print(full_text)
