"""
解码完整的 Agent 响应
"""
import json

# 从之前的测试输出中提取的响应内容
response_chunks = [
    '{"type": "session", "session_id": "85dc0510-aac0-438d-ac22-e6d6b74228fb"}',
    '{"type": "content", "content": "\\u597d\\u7684"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u7528\\u6237"}',
    '{"type": "content", "content": "\\u8ba9\\u6211"}',
    '{"type": "content", "content": "\\u8ba1\\u7b97"}',
    '{"type": "content", "content": "1"}',
    '{"type": "content", "content": "5"}',
    '{"type": "content", "content": "\\u4e58"}',
    '{"type": "content", "content": "\\u4ee5"}',
    '{"type": "content", "content": "2"}',
    '{"type": "content", "content": "3"}',
    '{"type": "content", "content": "\\u7b49\\u4e8e"}',
    '{"type": "content", "content": "\\u591a\\u5c11"}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\u9996\\u5148"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u6211"}',
    '{"type": "content", "content": "\\u9700\\u8981"}',
    '{"type": "content", "content": "\\u786e\\u8ba4"}',
    '{"type": "content", "content": "\\u7528\\u6237"}',
    '{"type": "content", "content": "\\u7684\\u9700\\u6c42"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u770b\\u8d77\\u6765"}',
    '{"type": "content", "content": "\\u662f\\u4e00\\u4e2a"}',
    '{"type": "content", "content": "\\u7b80\\u5355\\u7684"}',
    '{"type": "content", "content": "\\u4e58"}',
    '{"type": "content", "content": "\\u6cd5"}',
    '{"type": "content", "content": "\\u95ee\\u9898"}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\u4e0d\\u8fc7"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u4f5c\\u4e3a"}',
    '{"type": "content", "content": "AI"}',
    '{"type": "content", "content": "\\u52a9\\u624b"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u6211"}',
    '{"type": "content", "content": "\\u5e94\\u8be5"}',
    '{"type": "content", "content": "\\u4f7f\\u7528"}',
    '{"type": "content", "content": "\\u63d0\\u4f9b\\u7684"}',
    '{"type": "content", "content": "\\u5de5\\u5177"}',
    '{"type": "content", "content": "\\u6765"}',
    '{"type": "content", "content": "\\u5904\\u7406"}',
    '{"type": "content", "content": "\\u8fd9\\u4e2a"}',
    '{"type": "content", "content": "\\u8bf7\\u6c42"}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\n\\n\\u770b\\u4e00\\u4e0b"}',
    '{"type": "content", "content": "\\u53ef\\u7528"}',
    '{"type": "content", "content": "\\u7684"}',
    '{"type": "content", "content": "\\u5de5\\u5177"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u6709\\u4e00\\u4e2a"}',
    '{"type": "content", "content": "calculator"}',
    '{"type": "content", "content": "\\u51fd\\u6570"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u652f\\u6301"}',
    '{"type": "content", "content": "\\u57fa\\u672c"}',
    '{"type": "content", "content": "\\u8fd0\\u7b97"}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\u6240\\u4ee5"}',
    '{"type": "content", "content": "\\u5e94\\u8be5"}',
    '{"type": "content", "content": "\\u8c03"}',
    '{"type": "content", "content": "\\u7528"}',
    '{"type": "content", "content": "\\u8fd9\\u4e2a"}',
    '{"type": "content", "content": "\\u8ba1\\u7b97\\u5668"}',
    '{"type": "content", "content": "\\u5de5\\u5177"}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\u53c2\\u6570"}',
    '{"type": "content", "content": "\\u662f"}',
    '{"type": "content", "content": "expression"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u9700\\u8981"}',
    '{"type": "content", "content": "\\u628a"}',
    '{"type": "content", "content": "\\u8868\\u8fbe"}',
    '{"type": "content", "content": "\\u5f0f"}',
    '{"type": "content", "content": "\\u5199"}',
    '{"type": "content", "content": "\\u6210"}',
    '{"type": "content", "content": "\\u5b57\\u7b26\\u4e32"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u6bd4\\u5982"}',
    '{"type": "content", "content": "\\\""}',
    '{"type": "content", "content": "1"}',
    '{"type": "content", "content": "5"}',
    '{"type": "content", "content": " *"}',
    '{"type": "content", "content": " 2"}',
    '{"type": "content", "content": "3"}',
    '{"type": "content", "content": "\\\""}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\n\\n\\u4e0d\\u8fc7"}',
    '{"type": "content", "content": "\\u8981\\u6ce8\\u610f"}',
    '{"type": "content", "content": "\\u7684\\u662f"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u7528\\u6237"}',
    '{"type": "content", "content": "\\u53ef\\u80fd"}',
    '{"type": "content", "content": "\\u8f93\\u5165"}',
    '{"type": "content", "content": "\\u7684\\u662f"}',
    '{"type": "content", "content": "\\u4e2d\\u6587"}',
    '{"type": "content", "content": "\\u6570\\u5b57"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u4f46"}',
    '{"type": "content", "content": "\\u8fd9\\u91cc"}',
    '{"type": "content", "content": "1"}',
    '{"type": "content", "content": "5"}',
    '{"type": "content", "content": "\\u548c"}',
    '{"type": "content", "content": "2"}',
    '{"type": "content", "content": "3"}',
    '{"type": "content", "content": "\\u90fd\\u662f"}',
    '{"type": "content", "content": "\\u963f\\u62c9\\u4f2f"}',
    '{"type": "content", "content": "\\u6570\\u5b57"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u6240\\u4ee5"}',
    '{"type": "content", "content": "\\u76f4\\u63a5"}',
    '{"type": "content", "content": "\\u8ba1\\u7b97"}',
    '{"type": "content", "content": "\\u5c31\\u884c"}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\u786e\\u8ba4"}',
    '{"type": "content", "content": "\\u4e00\\u4e0b"}',
    '{"type": "content", "content": "\\u8ba1\\u7b97"}',
    '{"type": "content", "content": "\\u662f\\u5426"}',
    '{"type": "content", "content": "\\u6b63\\u786e"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "1"}',
    '{"type": "content", "content": "5"}',
    '{"type": "content", "content": "\\u4e58"}',
    '{"type": "content", "content": "2"}',
    '{"type": "content", "content": "3"}',
    '{"type": "content", "content": "\\u786e\\u5b9e\\u662f"}',
    '{"type": "content", "content": "3"}',
    '{"type": "content", "content": "4"}',
    '{"type": "content", "content": "5"}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\u4f46"}',
    '{"type": "content", "content": "\\u4f5c\\u4e3a"}',
    '{"type": "content", "content": "AI"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u5e94\\u8be5"}',
    '{"type": "content", "content": "\\u4e25\\u683c"}',
    '{"type": "content", "content": "\\u6309\\u7167"}',
    '{"type": "content", "content": "\\u5de5\\u5177"}',
    '{"type": "content", "content": "\\u7684"}',
    '{"type": "content", "content": "\\u4f7f\\u7528"}',
    '{"type": "content", "content": "\\u65b9\\u5f0f"}',
    '{"type": "content", "content": "\\u6765"}',
    '{"type": "content", "content": "\\u5904\\u7406"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u5373"}',
    '{"type": "content", "content": "\\u8c03"}',
    '{"type": "content", "content": "\\u7528"}',
    '{"type": "content", "content": "calculator"}',
    '{"type": "content", "content": "\\u51fd\\u6570"}',
    '{"type": "content", "content": "\\uff0c\\u5e76"}',
    '{"type": "content", "content": "\\u4f20"}',
    '{"type": "content", "content": "\\u5165"}',
    '{"type": "content", "content": "\\u6b63\\u786e\\u7684"}',
    '{"type": "content", "content": "\\u8868\\u8fbe"}',
    '{"type": "content", "content": "\\u5f0f"}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\n\\n\\u6240\\u4ee5"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u6b63\\u786e\\u7684"}',
    '{"type": "content", "content": "\\u505a\\u6cd5"}',
    '{"type": "content", "content": "\\u662f"}',
    '{"type": "content", "content": "\\u751f\\u6210"}',
    '{"type": "content", "content": "\\u4e00\\u4e2a"}',
    '{"type": "content", "content": "tool"}',
    '{"type": "content", "content": "_call"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u8c03"}',
    '{"type": "content", "content": "\\u7528"}',
    '{"type": "content", "content": "calculator"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u53c2\\u6570"}',
    '{"type": "content", "content": "expression"}',
    '{"type": "content", "content": "\\u8bbe"}',
    '{"type": "content", "content": "\\u4e3a"}',
    '{"type": "content", "content": "\\\""}',
    '{"type": "content", "content": "1"}',
    '{"type": "content", "content": "5"}',
    '{"type": "content", "content": " *"}',
    '{"type": "content", "content": " 2"}',
    '{"type": "content", "content": "3"}',
    '{"type": "content", "content": "\\\""}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "content", "content": "\\u7136\\u540e"}',
    '{"type": "content", "content": "\\u7b49\\u5f85"}',
    '{"type": "content", "content": "\\u5de5\\u5177"}',
    '{"type": "content", "content": "\\u8fd4\\u56de"}',
    '{"type": "content", "content": "\\u7ed3\\u679c"}',
    '{"type": "content", "content": "\\uff0c"}',
    '{"type": "content", "content": "\\u518d"}',
    '{"type": "content", "content": "\\u628a"}',
    '{"type": "content", "content": "\\u7ed3\\u679c"}',
    '{"type": "content", "content": "\\u544a\\u8bc9"}',
    '{"type": "content", "content": "\\u7528\\u6237"}',
    '{"type": "content", "content": "\\u3002"}',
    '{"type": "tool_call", "tool_call": {"id": "call_kgd45ae8", "function": {"index": 0, "name": "calculator", "arguments": {"expression": "15 * 23"}}}}',
    '{"type": "tool_start", "tool_name": "calculator"}',
    '{"type": "tool_result", "tool_name": "calculator", "result": {"success": true, "result": 345, "expression": "15 * 23"}}',
]

print("=" * 80)
print("Agent 的完整思考过程和工具调用")
print("=" * 80)

full_text = ""
for chunk in response_chunks:
    try:
        data = json.loads(chunk)
        if data.get('type') == 'content':
            full_text += data.get('content', '')
        elif data.get('type') == 'tool_call':
            print("\n" + "=" * 80)
            print("🛠️ 工具调用")
            print("=" * 80)
            tool_call = data.get('tool_call', {})
            func = tool_call.get('function', {})
            print(f"工具名称: {func.get('name')}")
            print(f"参数: {json.dumps(func.get('arguments'), indent=2, ensure_ascii=False)}")
        elif data.get('type') == 'tool_start':
            print(f"\n⏳ 开始执行工具: {data.get('tool_name')}")
        elif data.get('type') == 'tool_result':
            print(f"\n✅ 工具执行结果:")
            print(json.dumps(data.get('result'), indent=2, ensure_ascii=False))
    except:
        pass

print("\n" + "=" * 80)
print("🤖 Agent 的思考过程（解码后）")
print("=" * 80)
print(full_text)
